version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wzillityuqed"


[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wzillityuqed"
confirm_changeset = true


[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wzillityuqed"
